on:
  push:
  pull_request:
  merge_group:

name: CI
jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
        - 'pypy-3.8'
        - 'pypy-3.9'
        - 'pypy-3.10'
        allow-failure:
        - false
        include:
        - python-version: '3.13-dev'
          allow-failure: true
    continue-on-error: ${{ matrix.allow-failure }}
    name: 'test (${{ matrix.python-version }})'
    steps:
    - name: Check out source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys FA8E1301F4D3932C
        sudo add-apt-repository 'deb http://ppa.launchpad.net/sri-csl/formal-methods/ubuntu bionic main'
        sudo apt-get update
        sudo apt-get install yices2
        pip install codecov build
        pdm install --dev
    - name: Cache YoWASP build products
      uses: actions/cache@v4
      with:
        path: ~/.cache/YoWASP
        key: YoWASP-${{ runner.os }}-${{ hashFiles('./.venv/**/*.wasm') }}
        restore-keys: |
          YoWASP-${{ runner.os }}-
    - name: Run tests
      run: |
        pdm run test
    - name: Submit code coverage
      run: |
        codecov

  smoketest: # If we plug this into downstream projects, does magic smoke escape?
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - amaranth-lang/amaranth-boards
          - amaranth-lang/amaranth-stdio
          - amaranth-lang/amaranth-soc
    name: 'smoke (${{ matrix.project }})'
    steps:
    - name: Check out Amaranth source code
      uses: actions/checkout@v4
      with:
        path: amaranth
        fetch-depth: 0
    - name: Check out source code
      uses: actions/checkout@v4
      with:
        repository: ${{ matrix.project }}
        path: project
        fetch-depth: 0
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4
    - name: Install dependencies
      working-directory: project
      run: |
        pdm install --dev
    - name: Use Amaranth HEAD revision
      working-directory: project
      run: |
        pdm add ../amaranth
    - name: Cache YoWASP build products
      uses: actions/cache@v4
      with:
        path: ~/.cache/YoWASP
        key: YoWASP-${{ runner.os }}-${{ hashFiles('./.venv/**/*.wasm') }}
        restore-keys: |
          YoWASP-${{ runner.os }}-
    - name: Run tests
      working-directory: project
      run: |
        pdm run test
